// <auto-generated />
namespace ShopAdvisor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alter2PlaceTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter2PlaceTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201606140123032_Alter2PlaceTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
